name: Keep Website Alive

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Ping website
        run: curl --fail --silent --show-error "https://airesumeanalyzer-jeqbg9qli7k5wj4ndps3fs.streamlit.app/"
